// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6xY5UWU1lfdDTvWda2_1IUF9ooFtcv9g',
    appId: '1:44251978625:web:00c539e77b5dc6d9c5e680',
    messagingSenderId: '44251978625',
    projectId: 'flutter-giai-dap-thac-mac-app',
    authDomain: 'flutter-giai-dap-thac-mac-app.firebaseapp.com',
    storageBucket: 'flutter-giai-dap-thac-mac-app.firebasestorage.app',
    measurementId: 'G-C2NEM1MR90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzdHdGeYYN5wVN_9ppr51poVHozqk_Ab0',
    appId: '1:44251978625:android:a3b017166b8faee4c5e680',
    messagingSenderId: '44251978625',
    projectId: 'flutter-giai-dap-thac-mac-app',
    storageBucket: 'flutter-giai-dap-thac-mac-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUrNQAB03JeD-moraehBLqfRXP-gM8uM',
    appId: '1:44251978625:ios:545ef03ff7c27e37c5e680',
    messagingSenderId: '44251978625',
    projectId: 'flutter-giai-dap-thac-mac-app',
    storageBucket: 'flutter-giai-dap-thac-mac-app.firebasestorage.app',
    iosBundleId: 'com.example.appGdtm',
  );
}
